criaCartao('Geografia', 'Qual é o maior país do mundo?', 'A Rússia é o maior país do mundo em área territorial.')
criaCartao('História', 'Quem foi o primeiro imperador de Roma?', 'Augusto foi o primeiro imperador de Roma, governando de 27 a.C. a 14 d.C.')
criaCartao('Ciência', 'O que é a teoria da relatividade?', 'A teoria da relatividade de Einstein descreve como o espaço e o tempo são interligados e podem ser afetados pela gravidade e pela velocidade.')
criaCartao('Literatura', 'Quem escreveu "Dom Quixote"?', 'O autor de "Dom Quixote" foi Miguel de Cervantes.')
criaCartao('Artes', 'Qual movimento artístico é associado a Picasso?', 'O Cubismo é o movimento artístico associado a Pablo Picasso.')
criaCartao('Cinema', 'Quem dirigiu o filme "Titanic"?', 'James Cameron foi o diretor do filme "Titanic".')
criaCartao('Tecnologia', 'Quem fundou a Microsoft?', 'Bill Gates e Paul Allen fundaram a Microsoft em 1975.')
criaCartao('Espaço', 'Qual é o planeta mais próximo do Sol?', 'Mercúrio é o planeta mais próximo do Sol.')
criaCartao('Matemática', 'O que é o número Pi?', 'O número Pi é uma constante matemática que representa a razão entre a circunferência e o diâmetro de um círculo.')
criaCartao('Geografia', 'Qual é o maior deserto do mundo?', 'O maior deserto do mundo é o Deserto da Antártica, considerando sua área total como deserto polar.')
criaCartao('Biologia', 'O que é fotossíntese?', 'Fotossíntese é o processo pelo qual as plantas transformam luz solar em energia química, utilizando dióxido de carbono e água.')
criaCartao('Física', 'O que é a Lei da Gravitação Universal?', 'A Lei da Gravitação Universal de Newton afirma que dois corpos se atraem com uma força proporcional às suas massas e inversamente proporcional ao quadrado da distância entre eles.')
criaCartao('História', 'Quem foi Napoleão Bonaparte?', 'Napoleão Bonaparte foi um líder militar e imperador francês que dominou grande parte da Europa no início do século XIX.')
criaCartao('Política', 'O que é uma democracia?', 'Uma democracia é um sistema de governo onde o poder é exercido pelo povo, por meio de eleições diretas ou indiretas.')
criaCartao('Química', 'O que é o átomo?', 'O átomo é a unidade básica da matéria, composta por prótons, nêutrons e elétrons.')
criaCartao('Literatura', 'Quem é o autor de "Harry Potter"?', 'J.K. Rowling é a autora da série "Harry Potter".')
criaCartao('Música', 'Qual é o gênero musical originado no Brasil que mistura samba e jazz?', 'A Bossa Nova é o gênero musical originado no Brasil que mistura samba e jazz.')
criaCartao('Artes', 'Quem pintou "A Última Ceia"?', 'Leonardo da Vinci foi o autor da pintura "A Última Ceia".')
criaCartao('Cinema', 'Qual foi o primeiro filme a ganhar o Oscar de Melhor Filme?', 'O primeiro filme a ganhar o Oscar de Melhor Filme foi "Wings", em 1929.')
criaCartao('Espaço', 'O que é uma estrela?', 'Uma estrela é uma esfera de plasma quente que gera luz e calor através de reações nucleares em seu núcleo.')
criaCartao('Ciência', 'Quem descobriu a penicilina?', 'A penicilina foi descoberta por Alexander Fleming em 1928.')
criaCartao('Esportes', 'Quem detém o recorde mundial de 100 metros rasos?', 'O recorde mundial de 100 metros rasos pertence a Usain Bolt, com o tempo de 9,58 segundos.')
criaCartao('História', 'Quem foi Leonardo da Vinci?', 'Leonardo da Vinci foi um polímata italiano do Renascimento, famoso por suas pinturas, invenções e estudos científicos.')
criaCartao('Matemática', 'O que é um número primo?', 'Um número primo é aquele que só pode ser dividido por 1 e ele mesmo.')
criaCartao('Geografia', 'Qual é o maior rio do mundo?', 'O maior rio do mundo é o Rio Amazonas, com o maior volume de água.')
criaCartao('Política', 'O que é um parlamentarismo?', 'No parlamentarismo, o governo é formado por um primeiro-ministro e os ministros, sendo que o primeiro-ministro depende do apoio do parlamento.')
criaCartao('Literatura', 'Quem escreveu "Cem Anos de Solidão"?', 'Gabriel García Márquez escreveu "Cem Anos de Solidão".')
criaCartao('Tecnologia', 'Quem inventou o telefone?', 'Alexander Graham Bell é o inventor do telefone.')
criaCartao('Música', 'Quem compôs a "Nona Sinfonia"?', 'Ludwig van Beethoven compôs a "Nona Sinfonia".')
criaCartao('Filosofia', 'O que é o existencialismo?', 'O existencialismo é uma corrente filosófica que enfatiza a liberdade, a escolha individual e a responsabilidade humana.')
criaCartao('Artes', 'Quem pintou "Guernica"?', 'Pablo Picasso pintou "Guernica", uma obra que expressa os horrores da Guerra Civil Espanhola.')
criaCartao('Espaço', 'O que é uma supernova?', 'Uma supernova é uma explosão estelar extremamente brilhante que ocorre quando uma estrela morre.')
criaCartao('Ciência', 'O que é a teoria da evolução?', 'A teoria da evolução, proposta por Charles Darwin, sugere que as espécies evoluem ao longo do tempo por meio de seleção natural.')
criaCartao('Geografia', 'Onde está localizada a Grande Barreira de Coral?', 'A Grande Barreira de Coral está localizada no mar de Coral, na costa nordeste da Austrália.')
criaCartao('Tecnologia', 'O que é a inteligência artificial?', 'A inteligência artificial é o campo da ciência da computação que cria sistemas capazes de realizar tarefas que normalmente requerem inteligência humana.')
criaCartao('Física', 'O que é a energia cinética?', 'A energia cinética é a energia associada ao movimento de um objeto.')
criaCartao('Matemática', 'O que é a geometria?', 'A geometria é um ramo da matemática que estuda as propriedades e as relações dos pontos, linhas, superfícies e sólidos no espaço.')
criaCartao('Política', 'O que significa "separação de poderes"?', 'A separação de poderes é um princípio político que divide o governo em diferentes ramos: Executivo, Legislativo e Judiciário.')
criaCartao('Esportes', 'Onde foram os Jogos Olímpicos de 2008?', 'Os Jogos Olímpicos de 2008 aconteceram em Pequim, na China.')
criaCartao('História', 'Quando ocorreu a Revolução Francesa?', 'A Revolução Francesa ocorreu entre 1789 e 1799.')
criaCartao('Artes', 'Quem pintou "O Grito"?', 'Edvard Munch pintou "O Grito".')
criaCartao('Ciência', 'O que é um buraco negro?', 'Um buraco negro é uma região do espaço-tempo onde a gravidade é tão intensa que nada, nem mesmo a luz, pode escapar.')
criaCartao('Música', 'Qual é a origem do reggae?', 'O reggae é um gênero musical originado na Jamaica, com forte influência de ritmos africanos e do ska.')
criaCartao('Literatura', 'Quem escreveu "1984"?', 'George Orwell escreveu "1984".')
criaCartao('Tecnologia', 'O que é a realidade aumentada?', 'A realidade aumentada é uma tecnologia que sobrepõe elementos digitais ao mundo real, criando uma experiência interativa.')
criaCartao('Política', 'O que é um estado laico?', 'Um estado laico é aquele que não tem uma religião oficial e trata todas as crenças de maneira neutra.')
criaCartao('História', 'Qual foi a causa da Primeira Guerra Mundial?', 'A Primeira Guerra Mundial foi causada por uma combinação de fatores, incluindo nacionalismo, imperialismo, alianças militares e o assassinato do arquiduque Francisco Ferdinando.')
criaCartao('Esportes', 'Qual país ganhou a Copa do Mundo de Futebol de 2018?', 'A França venceu a Copa do Mundo de Futebol de 2018.')
criaCartao('Geografia', 'Qual é a capital do Japão?', 'Tóquio é a capital do Japão.')
criaCartao('Ciência', 'O que é a teoria do Big Bang?', 'A teoria do Big Bang sugere que o universo se originou a partir de uma grande explosão há cerca de 13,8 bilhões de anos.')
criaCartao('Matemática', 'O que é um ângulo reto?', 'Um ângulo reto é um ângulo de 90 graus.')
criaCartao('Filosofia', 'Quem foi Sócrates?', 'Sócrates foi um filósofo grego, conhecido por seu método de questionamento, que influenciou profundamente a filosofia ocidental.')
criaCartao('Artes', 'Qual é a famosa escultura criada por Michelangelo?', 'A famosa escultura de Michelangelo é "David".')
criaCartao('Cinema', 'Qual filme ganhou o Oscar de Melhor Filme em 1994?', 'Em 1994, o Oscar de Melhor Filme foi para "Forrest Gump".')
criaCartao('História', 'Quando foi a queda do Muro de Berlim?', 'O Muro de Berlim caiu em 9 de novembro de 1989.')
criaCartao('Esportes', 'Quem é considerado o maior jogador de basquete de todos os tempos?', 'Michael Jordan é considerado por muitos o maior jogador de basquete de todos os tempos.')




